### ISSUE TITLE
[next][create-threlte] Cannot import @threlte/flex with default config

### ISSUE THREAD

**Issue by wmurphyrd** [threlte/threlte#1111]
After bootstrapping a project with create-threlte and selecting the Svelte 5 option and all the threlte optional add-ons, attempting to import an use use @threlte/flex results in a vite error:

```
✘ [ERROR] Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)

    node_modules/yoga-layout/dist/src/index.js:13:26:
      13 │ const Yoga = wrapAssembly(await loadYoga());
         ╵                           ~~~~~

4:51:27 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/yoga-layout/dist/src/index.js:13:26: ERROR: Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)
    at failureErrorWithLog (/home/will/git/spatializeme/node_modules/esbuild/lib/main.js:1472:15)
    at /home/will/git/spatializeme/node_modules/esbuild/lib/main.js:945:25
    at /home/will/git/spatializeme/node_modules/esbuild/lib/main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) (x2)
```

My vite config:

```js
import { sveltekit } from '@sveltejs/kit/vite'
import { defineConfig } from 'vitest/config'
import basicSsl from '@vitejs/plugin-basic-ssl'

export default defineConfig({
  plugins: [basicSsl(), sveltekit()],
  test: {
    include: ['src/**/*.{test,spec}.{js,ts}']
  }
})
```

One workaround ([via SO](https://stackoverflow.com/a/77643886)) is to update the vite config as follows:

```
import { sveltekit } from '@sveltejs/kit/vite'
import { defineConfig } from 'vitest/config'
import basicSsl from '@vitejs/plugin-basic-ssl'

export default defineConfig({
  build: {
    target: "esnext"
  },
  optimizeDeps: {
    esbuildOptions: {
      target: 'esnext'
    }
  },
  plugins: [basicSsl(), sveltekit()],
  test: {
    include: ['src/**/*.{test,spec}.{js,ts}']
  }
})
```

**Comment by grischaerbe** [comment]
We decided to deprecate `npm create threlte` and want to implement a scaffolding by making use of Svelte's CLI `npx sv`.
