### ISSUE TITLE
Error while preprocessing: markup.update is not a function

### ISSUE THREAD

**Issue by DeepBhat** [threlte/threlte#255]
Hello,

I am trying to follow the docs at https://threlte.xyz/getting-started#installation. I am using Vite and Svelte (not SvelteKit), and I am getting this error while trying to run development server

```
[vite] Internal server error: Error while preprocessing Landing.svelte - markup.update is not a function
  Plugin: vite-plugin-svelte
  File: Landing.svelte
      at Object.enter (index.js:121:32)
      at SyncWalker.visit (node_modules/svelte/compiler.mjs:6211:16)
      at SyncWalker.visit (node_modules/svelte/compiler.mjs:6241:18)
      at SyncWalker.visit (node_modules/svelte/compiler.mjs:6241:18)
      at SyncWalker.visit (node_modules/svelte/compiler.mjs:6241:18)
      at SyncWalker.visit (node_modules/svelte/compiler.mjs:6248:11)
      at walk (node_modules/svelte/compiler.mjs:6299:18)
      at preprocessMarkup (node_modules/@threlte/preprocess/dist/index.js:41:5)
      at markup (node_modules/@threlte/preprocess/dist/index.js:158:32)
      at process_markup (node_modules\svelte\compiler.js:43406:30)
```

Could you please help me out? I do not understand why am I getting this error.

**Comment by grischaerbe** [comment]
Hey @DeepBhat, I guess a dependency of yours installed `magic-string` in a version prior to [0.26.6](https://github.com/rich-harris/magic-string/compare/v0.26.5...v0.26.6) which added the method `update`. Running `npm i -D magic-string` should resolve the issue.
