### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by Avi-ADAM** [threlte/threlte#313]
i get this error during development and production

```

"Three" is not exported by "node_modules/@threlte/core/dist/index.js", imported by "node_modules/@threlte/extras/dist/components/Grid/Grid.svelte".
--
19:50:53.958 | file: /vercel/path0/node_modules/@threlte/extras/dist/components/Grid/Grid.svelte:4:9
19:50:53.959 | 2: <script>
19:50:53.959 | 3: import { PlaneGeometry } from 'three';
19:50:53.959 | 4: import { Three } from '@threlte/core';
19:50:53.959 | ^
19:50:53.959 | 5: import { useThrelte } from '@threlte/core';
19:50:53.959 | 6: import { Color, ShaderMaterial, DoubleSide, Mesh } from 'three';
19:50:53.960 | error during build:
19:50:53.960 | RollupError: "Three" is not exported by "node_modules/@threlte/core/dist/index.js", imported by "node_modules/@threlte/extras/dist/components/Grid/Grid.svelte".
19:50:53.960 | at error (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
19:50:53.960 | at Module.error (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:13316:16)
19:50:53.960 | at Module.traceVariable (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:13701:29)
19:50:53.961 | at ModuleScope.findVariable (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:12204:39)
19:50:53.961 | at ReturnValueScope.findVariable (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:6950:38)
19:50:53.961 | at ChildScope.findVariable (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:6950:38)
19:50:53.961 | at BlockScope.findVariable (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:6950:38)
19:50:53.961 | at Identifier.bind (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:8100:40)
19:50:53.961 | at CallExpression.bind (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:5742:28)
19:50:53.961 | at CallExpression.bind (file:///vercel/path0/node_modules/rollup/dist/es/shared/node-entry.js:9627:15)
19:50:54.014 | error Command failed with exit code 1.
19:50:54.014 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
19:50:54.033 | Error: Command "yarn run build" exited with 1
19:50:54.722 | BUILD_FAILED: Command "yarn run build" exited with 1

```

in development ijust delited half of the grid file but on pruduction its not posible 
i am not using grid in my code also i can see that on github the grid code is diffrent ...

my package.json
```

"devDependencies": {
    "@sveltejs/kit": "1.3.10",
    "@threlte/extras": "^4.9.3",
    "layercake": "^6.1.0",
    "postcss-load-config": "^3.1.4",
    "svead": "^0.0.4",
    "svelte": "^3.53.1",
},
 "dependencies": {
    "@capacitor/android": "^3.6.0",
    "@capacitor/cli": "^3.6.0",
    "@capacitor/core": "^3.6.0",
    "@event-calendar/common": "^0.14.1",
    "@event-calendar/day-grid": "^0.14.1",
    "@fontsource/fira-mono": "^4.5.7",
    "@lottiefiles/svelte-lottie-player": "^0.2.0",
    "@okrad/svelte-progressbar": "^1.11.3",
    "@sendgrid/mail": "^7.7.0",
    "@sveltejs/adapter-static": "^1.0.0",
    "@threlte/core": "^4.3.3",
    "@threlte/preprocess": "^0.0.2",
    "axios": "^0.24.0",
    "blueimp-canvas-to-blob": "^3.29.0",
    "buffer": "^6.0.3",
    "cookie": "^0.4.2",
    "cssnano": "^5.1.7",
    "d3-format": "^3.1.0",
    "d3-geo": "^3.0.1",
    "d3-hierarchy": "^3.1.2",
    "d3-scale": "^4.0.2",
    "d3-shape": "^3.1.0",
    "dotenv": "^16.0.1",
    "jquery": "^3.6.0",
    "kit-sw-workbox": "^1.0.2",
    "local-access": "^1.1.0",
    "lodash.has": "^4.5.2",
    "lodash.isequal": "^4.5.0",
    "moment": "^2.29.2",
    "node": "^17.7.2",
    "postcss": "^8.4.12",
    "prettier": "^2.6.2",
    "prettier-plugin-svelte": "^2.7.0",
    "push.js": "^1.0.12",
    "quirrel": "^1.5.0",
    "socket.io": "^4.5.1",
    "socket.io-client": "^4.5.1",
    "svelte-accessible-dialog": "^2.1.3",
    "svelte-cloudinary": "^0.2.5",
    "svelte-confetti": "^1.2.0",
    "svelte-easy-crop": "^1.0.7",
    "svelte-forms-lib": "^2.0.1",
    "svelte-gantt": "^4.0.9-beta",
    "svelte-gestures": "^1.4.1",
    "svelte-mail": "^0.1.1",
    "svelte-preprocess": "^4.10.7",
    "svelte-sequential-preprocessor": "^1.0.0",
    "svelte-tour": "^1.0.7",
    "svelte-viewport-info": "^0.1.12",
    "sveltekit-i18n": "^2.1.4",
    "svelty-picker": "^3.0.0",
    "swiper": "^8.1.0",
    "three": "^0.148.0",
    "topojson-client": "^3.1.0",
    "vite": "^4.0.1",
    "yup": "^0.32.11"
  },
```

**Comment by Avi-ADAM** [comment]
i see that my core version is old when i updte its was ok
