### ISSUE TITLE
T still undefined after configuring preprocessor/sveltekit

### ISSUE THREAD

**Issue by brean** [threlte/threlte#335]
Hey,
I am using sveltekit and I am getting this error when using any of the "<T." tags:
(browser console log)
```
The component <T> can only be used in conjunction with the custom preprocessor.
```
I followed the installation instructions from the **Getting Started** section, so my vite-config looks like this:
```
import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
	plugins: [sveltekit()],
	ssr: {
		noExternal: ['three', 'troika-three-text']
	}
});
```

I tried to use the prepropessor, something like this for my svelte.config.js:
```
import adapter from '@sveltejs/adapter-auto';
import seqPreprocessor from 'svelte-sequential-preprocessor'
import { vitePreprocess } from '@sveltejs/kit/vite';
import { preprocessThrelte } from '@threlte/preprocess';


/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: seqPreprocessor([vitePreprocess(), preprocessThrelte()]),

	kit: {
		adapter: adapter()
	}
};

export default config;
```
which gives me the errors (browser console log):
```
[HMR][Svelte] Unrecoverable HMR error in <Root>: next update will trigger a full reload
logError @ proxy.js?v=1204e312:15
Proxy<Root> @ proxy.js?v=1204e312:380
initialize @ client.js?v=1204e312:447
_hydrate @ client.js?v=1204e312:1795
await in _hydrate (async)
start @ start.js:22
(anonymous) @ cube:35
Promise.then (async)
(anonymous) @ cube:34
+page.svelte? [sm]:12 Uncaught (in promise) ReferenceError: T is not defined
    at Array.create_default_slot_1 (+page.svelte? [sm]:12:37)
    at create_slot (index.mjs:71:28)
    at Array.create_default_slot27 (Three.svelte:74:32)
    at create_slot (index.mjs:71:28)
    at Array.create_default_slot (HierarchicalObject.svelte:65:26)
    at create_slot (index.mjs:71:28)
    at create_fragment (useThrelte.js:4:1)
    at init (index.mjs:2137:37)
    at new HierarchicalObject (HierarchicalObject.svelte:65:26)
    at create_fragment2 (HierarchicalObject.svelte:65:26)
```
but the first error `The component <T> ...` is gone.

So what is the correct way to use threlte with sveltekit and typescript? Is there a full example project somewhere that just builds?
I have my code here: https://github.com/brean/svelte-3d-urdf

**Comment by brean** [comment]
I got it running! I had to use <OrbitControls /> instead of <T.OrbitControls />.
Very misleading error message but at least its working now...
