### ISSUE TITLE
No matching export in "node_modules/three/build/three.module.js" for import "CylinderBufferGeometry"

### ISSUE THREAD

**Issue by robotpapier** [threlte/threlte#446]
Hi,
Just installed Threlte on Sveltekit (Svelte 3.54).
Succeeded with the getting started tutorial and get to see the Cube

But when trying to set the animation example, I have this error :  
``` 
VITE v4.3.9  ready in 1877 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
02:26:40 [vite-plugin-svelte] /src/routes/(three)/three/animation/+page.svelte:35:5 'action' is not defined
X [ERROR] No matching export in "node_modules/three/build/three.module.js" for import "CylinderBufferGeometry"

    node_modules/troika-three-utils/dist/troika-three-utils.esm.js:1:131:
      1 │ ...tils, MeshDepthMaterial, RGBADepthPacking, MeshDistanceMaterial, ShaderLib, Matrix4, Vector3, Mesh, CylinderBufferGeometry, Vector2, MeshStandardMaterial, DoubleSide } from 'three'; 
        ╵                                                                                                        ~~~~~~~~~~~~~~~~~~~~~~

02:26:53 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/troika-three-utils/dist/troika-three-utils.esm.js:1:131: ERROR: No matching export in "node_modules/three/build/three.module.js" for import "CylinderBufferGeometry"
    at failureErrorWithLog (D:\my-skeleton-app3\node_modules\esbuild\lib\main.js:1636:15)
    at D:\my-skeleton-app3\node_modules\esbuild\lib\main.js:1048:25
    at D:\my-skeleton-app3\node_modules\esbuild\lib\main.js:1512:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
02:26:53 [vite-plugin-svelte] /src/routes/(three)/three/animation/+page.svelte:35:5 'action' is not defined
X [ERROR] No matching export in "node_modules/three/build/three.module.js" for import "PlaneBufferGeometry"

    node_modules/@threlte/extras/dist/components/ContactShadows/ContactShadows.svelte:37:1:
      37 │   PlaneBufferGeometry,
         ╵   ~~~~~~~~~~~~~~~~~~~

X [ERROR] No matching export in "node_modules/three/build/three.module.js" for import "CylinderBufferGeometry"

    node_modules/troika-three-utils/dist/troika-three-utils.esm.js:1:131:
      1 │ ...tils, MeshDepthMaterial, RGBADepthPacking, MeshDistanceMaterial, ShaderLib, Matrix4, Vector3, Mesh, CylinderBufferGeometry, Vector2, MeshStandardMaterial, DoubleSide } from 'three';
        ╵                                                                                                        ~~~~~~~~~~~~~~~~~~~~~~

X [ERROR] No matching export in "node_modules/three/build/three.module.js" for import "PlaneBufferGeometry"

    node_modules/troika-three-text/dist/troika-three-text.esm.js:1:126:
      1 │ ...edBufferGeometry, Sphere, Box3, BackSide, DoubleSide, InstancedBufferAttribute, PlaneBufferGeometry, BufferGeometry, Float32BufferAttribute, Vector2, Vector4, Matrix3, MeshBasicM...
        ╵                                                                                    ~~~~~~~~~~~~~~~~~~~

02:26:57 [vite] error while updating dependencies:
Error: Build failed with 3 errors:
node_modules/@threlte/extras/dist/components/ContactShadows/ContactShadows.svelte:37:1: ERROR: No matching export in "node_modules/three/build/three.module.js" for import "PlaneBufferGeometry"   
node_modules/troika-three-text/dist/troika-three-text.esm.js:1:126: ERROR: No matching export in "node_modules/three/build/three.module.js" for import "PlaneBufferGeometry"
node_modules/troika-three-utils/dist/troika-three-utils.esm.js:1:131: ERROR: No matching export in "node_modules/three/build/three.module.js" for import "CylinderBufferGeometry"
    at failureErrorWithLog (D:\my-skeleton-app3\node_modules\esbuild\lib\main.js:1636:15)
    at D:\my-skeleton-app3\node_modules\esbuild\lib\main.js:1048:25
    at D:\my-skeleton-app3\node_modules\esbuild\lib\main.js:1512:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
Does anyone encoutered this ?

That is besides having to Rename GroundProjectedSkybox.js to solve the bug mentionned here : https://stackoverflow.com/questions/76282026/how-can-i-fix-the-threlte-extras-import-error-sveltekit/76288767#76288767

as well as  solving this error by using { browser } from '$app/environment'
`Error: useTweakpane can only be used in the browser`

**Comment by robotpapier** [comment]
Re,
ok what confused me is that there is a new version Threlte 6 and I was using examples with deprecated components of Threlte 5
New documentation here
[https://next.threlte.xyz/](url)

Now it's working :)
