### ISSUE TITLE
@threlte/theatre causes sveltekit build to fail

### ISSUE THREAD

**Issue by roelvanhintum** [threlte/threlte#478]
In a typescript sveltekit project `@threlte/theatre` causes errors on build using `@sveltejs/adapter-static`.

```
import { pick, omit } from "lodash";
               ^^^^
SyntaxError: Named export 'omit' not found. The requested module 'lodash' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'lodash';
const { pick, omit } = pkg;
```

Edit: also happening on @threlte/theatre@1.0.2

**Comment by roelvanhintum** [comment]
This is awkward, the issue has moved:
```
import { onChange as onChange$1, val as val$1 } from "@theatre/core";
         ^^^^^^^^
SyntaxError: Named export 'onChange' not found. The requested module '@theatre/core' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@theatre/core';
const { onChange: onChange$1, val: val$1 } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:122:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:188:5)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:228:24)
```

**Comment by grischaerbe** [comment]
Can you check if the error disappears if in production you add this to your vite config: 

```ts
const config = {
  // …
  ssr: {
    noExternal: [/* other libs */, '@theatre/core']
  }
}
```

We're experiencing the [same issue in our docs](https://github.com/threlte/threlte/blob/main/apps/docs/astro.config.ts).

**Comment by roelvanhintum** [comment]
Thanks @grischaerbe! That seems to solve it.

**Comment by janosh** [comment]
I just saw a similar error with `@threlte/extras`:


```
SyntaxError: [vite] Named export 'pick' not found. The requested module 'lodash' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'lodash';
const {omit, pick} = pkg;

    at analyzeImportedModDifference (/site/node_modules/.pnpm/vite@5.0.11/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:50953:19)
    at nodeImport (/site/node_modules/.pnpm/vite@5.0.11/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:50904:9)
    at async ssrImport (/site/node_modules/.pnpm/vite@5.0.11/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:50799:24)
    at async eval (/site/node_modules/.pnpm/@threlte+extras@5.0.0-next.16_three@0.154.0/node_modules/@threlte/extras/dist/components/controls/TransformControls/TransformControls.svelte:5:31)
    at async instantiateModule (/site/node_modules/.pnpm/vite@5.0.11/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:50861:9)
SvelteKitError: Not found: /favicon.ico
    at resolve (/site/node_modules/.pnpm/@sveltejs+kit@2.0.6_@sveltejs+vite-plugin-svelte@3.0.1_svelte@4.2.8_vite@5.0.11/node_modules/@sveltejs/kit/src/runtime/server/respond.js:485:13)
```

Adding 

```ts
  ssr: {
    noExternal: [`@threlte/extras`],
  },
```

didn't help but

```ts
  ssr: {
    noExternal: [`lodash`],
  },
```

did.
